### ISSUE TITLE
Can I have multiple tags?

### ISSUE THREAD

**Issue by mirkea-work** [bgashler1/vscode-htmltagwrap#11]
Can I choose between multiple tags? For example in same cases I might want to wrap a selection  with P, other times it might be a DIV

**Comment by bgashler1** [comment]
Hi @mirkea, you can change the type of tag after wrapping. The first thing you type after wrapping will be the new tag name applied to both the closing and opening tag.

You can also change the default tag inserted (e.g. to be a `div` instead of `p`) with the setting `"htmltagwrap.tag": "div"`. If this doesn't address your concern, please feel free to reopen.

**Comment by mirkea-work** [comment]
@bgashler1 thanks Brad. I must have missed that functionality but it works like you said which is great.
