### ISSUE TITLE
Glyph area

### ISSUE THREAD

**Issue by derricck** [bgashler1/vscode-htmltagwrap#35]
Hello, i couldn't find an email to get in contact with you
I've seen this gif that you posted in a vscode issue about the glyph area:

![51454928-e5ee-11e5-8416-16a62c9a12db](https://user-images.githubusercontent.com/105561748/229530580-0cf1e35a-821e-46e3-ae08-275adefe6436.gif)

Do you mind telling how you styled the folding icons [+] [-], the line width, color, place, like on your gif? It looks almost the same than on **Visual Studio** which was exactly what i was trying to achieve.

I mean:
![image](https://user-images.githubusercontent.com/105561748/229531158-a88924e0-a86d-4933-b3b2-cd59f6436370.png)

I have download an extension named "Minimalist Product Icon Theme" but it looks weird, also looks where the line is placed:
![image](https://user-images.githubusercontent.com/105561748/229530170-f28dc8c0-7746-4818-98e5-5b8498d11073.png)

under "app" instead being placed under the [-] icon like on your gif.

**Comment by bgashler1** [comment]
It's been a long time since I made that GIF and I forgot if it was actually in code that I made it or just an animation from my design tools. I believe it was the latter. I used the [Visual Studio icon library](https://www.microsoft.com/en-us/download/details.aspx?id=35825) at the time.
`.monaco-editor .lines-content .core-guide-indent` and `margin-view-overlays .cldr .someiconname` are some relevant styles, but it might not be allowed to be styled from extensions. Sorry I can't be more helpful.
