### ISSUE TITLE
command 'extension.htmlTagWrap' not found

### ISSUE THREAD

**Issue by ilchoTaleski** [bgashler1/vscode-htmltagwrap#38]
I am on a Mac and when using Option + W, a warning message from VSCode appears: command 'extension.htmlTagWrap' not found.

![image](https://user-images.githubusercontent.com/36581814/230798884-466c3762-7d40-4285-995b-fbd1e98aaeaa.png)

I tried restarting VSCode, uninstalling and installing the extension again, but it did not help.

I used Help + Toggle Developer Tools to open the console. This issue appears when I use the command:

Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform

![image](https://user-images.githubusercontent.com/36581814/230798864-ba3b4c7e-549f-4cfd-bdd2-71f17efde0ec.png)

**Comment by alosktx** [comment]
Have you solved it bro？I had the same problem and don't know how to fix it

**Comment by nuxcodes** [comment]
> Have you solved it bro？I had the same problem and don't know how to fix it

Downgrade to 0.0.7

**Comment by alosktx** [comment]
> > Have you solved it bro？I had the same problem and don't know how to fix it
> 
> Downgrade to 0.0.7

Thanks, I'll try it.

**Comment by charlestbell** [comment]
plus 1 
I'm also experiencing this.

**Comment by bgashler1** [comment]
@ilchoTaleski, I can't reproduce this issue and need some more info to investigate:
- What version of macOS are you using?
- What version of VS Code are you running?
- Are you using Stable (blue icon), Insiders (green icon) version of VS Code?
- Does this issue happen when you disable all other extensions? To try this, go to Extensions panel and disable all extensions followed by enabling just `htmltagwrap` by clicking on the gear icon
![Screenshot from 2023-06-08 21-27-47](https://github.com/bgashler1/vscode-htmltagwrap/assets/11839736/7d68b4db-4c07-423f-b3bd-8278cbcaa64d)


I don't recommend downgrading to 0.0.7 because some significant bugfixes are in the latest version.

**Comment by alosktx** [comment]
@bgashler1, I can give you more information to investigate it. 
I reproduced this issue by disabling all other extensions and only enable 'htmltagwrap'  of v0.0.9，as shown in the following figure.
![Screenshot from 2023-06-09 14-22-17](https://github.com/bgashler1/vscode-htmltagwrap/assets/35099886/42684054-1cad-4b3d-96bd-cc0f6bc492b5)
More info about the configuration and environment:
- Inter core i5-9300H
- vscode of stable version 1.70.2
- ubuntu of version 22.04.1
- ![Screenshot from 2023-06-09 14-41-31](https://github.com/bgashler1/vscode-htmltagwrap/assets/35099886/2be7ea03-e6f0-4c98-9111-212835da147a)

**Comment by bgashler1** [comment]
@ilchoTaleski, can you verify this is broken after you uninstall the extension completely, close VS Code, and reinstall the extension (at the latest version)? If so, does it also happen after you reinstall VS Code?

**Comment by charlestbell** [comment]
@bgashler1 Can confirm. I followed the steps you gave and same issue. "command 'extension.htmlTagWrap' not found"

Windows 11, the latest version of vscode.

**Comment by sangho1989** [comment]
> How to downgrade???

**Comment by bgashler1** [comment]
![image](https://github.com/bgashler1/vscode-htmltagwrap/assets/11839736/7c3c8ae6-3966-4f1d-a3d9-68aa9fbb01ae)

@sangho1989 here's how to temporarily install `0.0.7` while we root cause the issue for people affected.

I'm having a difficult time reproducing this issue. I can't repro on Mac, Linux or Windows. My hypothesis is that people who used version `0.0.7` and then upgraded are experiencing VS Code looking at cached old copies of part of the extension.

**Comment by bgashler1** [comment]
Update: I finally am able to repro it on Ubuntu VM using same config as alosktx above by installing the same old version of VS Code, the htmltagwrap extension, downgrading it to `0.0.7` and then upgrading it back to `0.0.9`. I'm investigating it now...

**Comment by bgashler1** [comment]
@alosktx , here's what fixed the error for me:
1) Uninstall (don't upgrade) VS Code
2) Download the latest [`.deb` installer for VS Code](https://code.visualstudio.com/docs/?dv=linux64_deb) (`1.80.2 currently) or download it from the "Ubuntu Software Center"
3) Install Htmltagwrap extension (which will be the latest 0.0.9 version) and press `alt + w` on  selection of text to wrap

The above fixed the error of `command 'extension.htmlTagWrap' not found` for me when I was using the latest version of this extension (`0.0.9`). If you still have issues. You can delete the `~/.config/Code` and ~/.vscode` folders respectively and then reinstall VS Code.

Can you confirm if this fixes your issue?

**Comment by alosktx** [comment]
@bgashler1 , Following your method I solved the problem and it did work, thanks.

**Comment by bgashler1** [comment]
@charlestbell and @ilchoTaleski, this should be fixed now after you update the extension to v1.0.0. Let me know if not.
